development:
  adapter: postgresql
  encoding: utf8
  database: db/mblog_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: utf8
  database: db/mblog_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: utf8
  database: db/mblog_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432